### ISSUE TITLE
Add support for gateway security policies

### ISSUE THREAD

**Issue by mike-r-mclaughlin** [AviatrixSystems/go-aviatrix#3]
APIs:
https://s3-us-west-2.amazonaws.com/avx-apidoc/index.htm
- list_profile_policies
- update_profile_policy
- vpc_access_policy
- set_vpc_base_policy
- update_access_policy
- Others?

Use case:
Need to be able to add Gateway security policies to a specific Gateway and also to remove from Go (and terraform).
Also - need to be able to add FQDN policies and attach Gateway.

**Comment by arvindsree** [comment]
Present in fqdn.go and firewall.go
